const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('browserAPI', {
  navigate: (targetUrl) => ipcRenderer.invoke('browser:navigate', targetUrl),
  openFile: () => ipcRenderer.invoke('browser:open-file'),
  setTheme: (theme) => ipcRenderer.invoke('browser:set-theme', theme),
  getTheme: () => ipcRenderer.invoke('browser:get-theme'),
  getSettings: () => ipcRenderer.invoke('browser:get-settings'),
  updateSettings: (settings) => ipcRenderer.invoke('browser:update-settings', settings),
  getDownloadDir: () => ipcRenderer.invoke('browser:get-download-dir'),
  pickDownloadDir: () => ipcRenderer.invoke('browser:pick-download-dir'),
  listExtensions: () => ipcRenderer.invoke('browser:list-extensions'),
  loadExtension: (extensionDir) => ipcRenderer.invoke('browser:load-extension', extensionDir),
  unloadExtension: (extensionId) => ipcRenderer.invoke('browser:unload-extension', extensionId),
  pickExtensionDir: () => ipcRenderer.invoke('browser:pick-extension-dir'),
  getDownloads: () => ipcRenderer.invoke('browser:get-downloads'),
  openDownloadLocation: (savePath) => ipcRenderer.invoke('browser:open-download-location', savePath),
  getAiConfig: () => ipcRenderer.invoke('browser:get-ai-config'),
  readAiConfig: () => ipcRenderer.invoke('browser:read-ai-config'),
  writeAiConfig: (config) => ipcRenderer.invoke('browser:write-ai-config', config),
  getAiKeyDebug: () => ipcRenderer.invoke('browser:get-ai-key-debug'),
  onThemeChanged: (callback) => ipcRenderer.on('theme-changed', (_, theme) => callback(theme)),
  onSettingsUpdated: (callback) => ipcRenderer.on('settings-updated', (_, settings) => callback(settings)),
  onAiConfigUpdated: (callback) => ipcRenderer.on('ai-config-updated', (_, config) => callback(config)),
  onOpenUrl: (callback) => ipcRenderer.on('open-url', (_, value) => callback(value)),
  onOpenPdf: (callback) => ipcRenderer.on('open-pdf', (_, value) => callback(value)),
  onDownloadsUpdated: (callback) => ipcRenderer.on('downloads-updated', (_, downloads) => callback(downloads)),
  onExtensionsUpdated: (callback) => ipcRenderer.on('extensions-updated', (_, extensions) => callback(extensions)),
  onShortcutNewTab: (callback) => ipcRenderer.on('shortcut:new-tab', () => callback()),
  onShortcutReopenTab: (callback) => ipcRenderer.on('shortcut:reopen-tab', () => callback()),
  onShortcutHome: (callback) => ipcRenderer.on('shortcut:home', () => callback()),
  onShortcutDownloads: (callback) => ipcRenderer.on('shortcut:downloads', () => callback()),
  onShortcutBookmarks: (callback) => ipcRenderer.on('shortcut:bookmarks', () => callback()),
  onShortcutExtensions: (callback) => ipcRenderer.on('shortcut:extensions', () => callback()),
  onShortcutSettings: (callback) => ipcRenderer.on('shortcut:settings', () => callback()),
  onShortcutFocusAddress: (callback) => ipcRenderer.on('shortcut:focus-address', () => callback()),
  onShortcutCloseTab: (callback) => ipcRenderer.on('shortcut:close-tab', () => callback()),
  onShortcutNextTab: (callback) => ipcRenderer.on('shortcut:next-tab', () => callback()),
  onShortcutPreviousTab: (callback) => ipcRenderer.on('shortcut:previous-tab', () => callback()),
  onShortcutTabIndex: (callback) => ipcRenderer.on('shortcut:tab-index', (_, index) => callback(index)),
  onShortcutHistory: (callback) => ipcRenderer.on('shortcut:history', () => callback())
});