const STORAGE_KEYS = {
  bookmarks: 'browser-desktop-bookmarks',
  history: 'browser-desktop-history',
  settings: 'browser-desktop-settings',
  ai: 'browser-desktop-ai'
};
const defaultSettings = { searchEngine: 'https://www.google.com/search?q=', homepage: 'https://www.google.com', openLinksInNewTab: true, theme: 'system', downloadDir: '' };
const defaultAi = { apiKey: '', model: 'deepseek-v4-flash' };
const state = { tabs: [], activeTabId: null, theme: 'system', bookmarks: loadJson(STORAGE_KEYS.bookmarks, []), history: loadJson(STORAGE_KEYS.history, []), downloads: [], extensions: [], settings: { ...defaultSettings, ...loadJson(STORAGE_KEYS.settings, {}) }, ai: { ...defaultAi, ...loadJson(STORAGE_KEYS.ai, {}) }, closedTabs: [], messages: [] };
const tabStrip = document.getElementById('tabStrip'); const webview = document.getElementById('activeWebview'); const addressBar = document.getElementById('addressBar'); const browserStage = document.getElementById('browserStage'); const welcomeScreen = document.getElementById('welcomeScreen'); const extensionList = document.getElementById('extensionList'); const app = document.getElementById('app'); const bookmarksList = document.getElementById('bookmarksList'); const historyList = document.getElementById('historyList'); const downloadsList = document.getElementById('downloadsList'); const searchInput = document.getElementById('searchInput'); const settingsPanel = document.getElementById('settingsPanel'); const bookmarkName = document.getElementById('bookmarkName'); const homepageInput = document.getElementById('homepageInput'); const searchEngineInput = document.getElementById('searchEngineInput'); const downloadDirInput = document.getElementById('downloadDirInput'); const openLinksInNewTabInput = document.getElementById('openLinksInNewTabInput'); const aiSidebar = document.getElementById('aiSidebar'); const aiChat = document.getElementById('aiChat'); const aiPromptInput = document.getElementById('aiPromptInput'); const aiModelSelect = document.getElementById('aiModelSelect'); const aiKeyInput = document.getElementById('aiKeyInput');
function loadJson(key, fallback) { try { const raw = localStorage.getItem(key); return raw ? JSON.parse(raw) : fallback; } catch { return fallback; } }
function saveJson(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
function normalizeUrl(input) { const value = input.trim(); if (!value) return state.settings.homepage; if (/^[a-zA-Z]+:\/\//.test(value) || value.startsWith('file://')) return value; if (value.endsWith('.html') || value.endsWith('.htm') || value.endsWith('.pdf')) return `file:///${value.replace(/\\/g, '/')}`; if (value.includes('.') && !value.includes(' ')) return `https://${value}`; return `${state.settings.searchEngine}${encodeURIComponent(value)}`; }
function escapeHtml(text) { return String(text).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;'); }
function syncSettingsUI() { homepageInput.value = state.settings.homepage || ''; searchEngineInput.value = state.settings.searchEngine || ''; downloadDirInput.value = state.settings.downloadDir || ''; openLinksInNewTabInput.checked = !!state.settings.openLinksInNewTab; aiModelSelect.value = state.ai.model; aiKeyInput.value = state.ai.apiKey ? '********' : ''; }
function createTab(url = state.settings.homepage, title = '新标签页') { const tab = { id: `tab-${Date.now()}-${Math.random().toString(16).slice(2)}`, url, title }; state.tabs.push(tab); state.activeTabId = tab.id; renderTabs(); loadTab(tab); toggleEmptyState(); }
function reopenClosedTab() { const tab = state.closedTabs.pop(); if (tab) createTab(tab.url, tab.title); }
function closeTab(id) { const index = state.tabs.findIndex(tab => tab.id === id); if (index === -1) return; const wasActive = state.activeTabId === id; state.closedTabs.push(state.tabs[index]); state.tabs.splice(index, 1); if (wasActive) { const nextTab = state.tabs[index] || state.tabs[index - 1]; state.activeTabId = nextTab?.id || null; if (nextTab) loadTab(nextTab); } renderTabs(); toggleEmptyState(); }
function activateTabByIndex(index) { const tab = state.tabs[index]; if (!tab) return; state.activeTabId = tab.id; renderTabs(); loadTab(tab); }
function moveTab(delta) { if (!state.tabs.length) return; const index = Math.max(0, state.tabs.findIndex(tab => tab.id === state.activeTabId)); const nextIndex = (index + delta + state.tabs.length) % state.tabs.length; activateTabByIndex(nextIndex); }
function loadTab(tab) { if (!tab) return; browserStage.classList.remove('hidden'); welcomeScreen.classList.add('hidden'); webview.src = tab.url; addressBar.value = tab.url; }
function renderTabs() { tabStrip.innerHTML = ''; state.tabs.forEach((tab, index) => { const tabEl = document.createElement('button'); tabEl.className = `tab ${tab.id === state.activeTabId ? 'active' : ''}`; tabEl.innerHTML = `<span class="tab-title">${escapeHtml(tab.title)}</span><span class="tab-close">×</span>`; tabEl.querySelector('.tab-close').addEventListener('click', (event) => { event.stopPropagation(); closeTab(tab.id); }); tabEl.addEventListener('click', () => { state.activeTabId = tab.id; renderTabs(); loadTab(tab); }); tabEl.title = `标签 ${index + 1}`; tabStrip.appendChild(tabEl); }); }
function toggleEmptyState() { const hasTabs = state.tabs.length > 0; welcomeScreen.classList.toggle('hidden', hasTabs); browserStage.classList.toggle('hidden', !hasTabs); }
function refreshBookmarks() { bookmarksList.innerHTML = ''; if (!state.bookmarks.length) { bookmarksList.innerHTML = '<div class="list-item muted">暂无书签</div>'; return; } state.bookmarks.forEach((item, index) => { const row = document.createElement('button'); row.className = 'list-item'; row.innerHTML = `<span>${escapeHtml(item.name)}</span><small>${escapeHtml(item.url)}</small>`; row.addEventListener('click', () => createTab(item.url, item.name)); const remove = document.createElement('span'); remove.className = 'remove'; remove.textContent = '删除'; remove.addEventListener('click', (event) => { event.stopPropagation(); state.bookmarks.splice(index, 1); saveJson(STORAGE_KEYS.bookmarks, state.bookmarks); refreshBookmarks(); }); row.appendChild(remove); bookmarksList.appendChild(row); }); }
function refreshHistory() { historyList.innerHTML = ''; const recent = [...state.history].slice(-12).reverse(); if (!recent.length) { historyList.innerHTML = '<div class="list-item muted">暂无历史记录</div>'; return; } recent.forEach(entry => { const row = document.createElement('button'); row.className = 'list-item'; row.innerHTML = `<span>${escapeHtml(entry.title)}</span><small>${escapeHtml(entry.url)}</small>`; row.addEventListener('click', () => createTab(entry.url, entry.title)); historyList.appendChild(row); }); }
function refreshDownloads() { downloadsList.innerHTML = ''; if (!state.downloads.length) { downloadsList.innerHTML = '<div class="list-item muted">暂无下载任务</div>'; return; } state.downloads.forEach(item => { const row = document.createElement('button'); row.className = 'list-item'; const percent = item.totalBytes ? Math.floor((item.receivedBytes / item.totalBytes) * 100) : 0; row.innerHTML = `<span>${escapeHtml(item.fileName)}</span><small>${escapeHtml(item.state)} · ${percent}%</small><div class="download-progress"><span style="width:${percent}%"></span></div>`; row.addEventListener('click', () => window.browserAPI.openDownloadLocation(item.savePath)); downloadsList.appendChild(row); }); }
function refreshExtensions() { extensionList.innerHTML = ''; if (!state.extensions.length) { extensionList.innerHTML = '<div class="extension-item">暂无已加载插件</div>'; return; } state.extensions.forEach(ext => { const row = document.createElement('div'); row.className = 'extension-item'; row.innerHTML = `<div><strong>${escapeHtml(ext.name)}</strong><div>${escapeHtml(ext.version)} · ${escapeHtml(ext.id)}</div></div><button data-unload="${escapeHtml(ext.id)}">移除</button>`; row.querySelector('button').addEventListener('click', async () => { await window.browserAPI.unloadExtension(ext.id); }); extensionList.appendChild(row); }); }
function renderAiChat() { aiChat.innerHTML = ''; if (!state.messages.length) { aiChat.innerHTML = '<div class="ai-msg assistant">你好，我是你的侧边栏 AI 助手。你可以让我总结网页、解释内容，或者直接回答问题。</div>'; return; } state.messages.forEach(msg => { const el = document.createElement('div'); el.className = `ai-msg ${msg.role}`; el.textContent = msg.content; aiChat.appendChild(el); }); aiChat.scrollTop = aiChat.scrollHeight; }
function addAiMessage(role, content) { state.messages.push({ role, content }); renderAiChat(); }
function getPageText() { const title = document.title || ''; const url = location.href; const selection = window.getSelection()?.toString() || ''; return `页面标题：${title}\n页面链接：${url}\n选中文本：${selection || '无'}\n\n请基于当前页面内容进行总结。`; }
async function callDeepSeek(prompt) { if (!state.ai.apiKey) throw new Error('请先设置 DeepSeek API Key'); const response = await fetch('https://api.deepseek.com/chat/completions', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${state.ai.apiKey}` }, body: JSON.stringify({ model: state.ai.model, messages: [ { role: 'system', content: '你是一个嵌入在浏览器侧边栏中的 AI 助手，回答要简洁、准确、友好。' }, ...state.messages.map(msg => ({ role: msg.role, content: msg.content })), { role: 'user', content: prompt } ], stream: false }) }); if (!response.ok) throw new Error(`DeepSeek 请求失败：${response.status}`); const data = await response.json(); return data?.choices?.[0]?.message?.content?.trim() || '没有返回结果'; }
async function sendPrompt(prompt) { const text = prompt.trim(); if (!text) return; addAiMessage('user', text); aiPromptInput.value = ''; addAiMessage('assistant', '正在思考...'); const loadingIndex = state.messages.length - 1; try { const answer = await callDeepSeek(text); state.messages[loadingIndex] = { role: 'assistant', content: answer }; renderAiChat(); } catch (error) { state.messages[loadingIndex] = { role: 'assistant', content: `调用失败：${error.message}` }; renderAiChat(); } }
function addHistory(url, title) { if (!url) return; const entry = { url, title: title || url, time: Date.now() }; state.history.push(entry); state.history = state.history.slice(-200); saveJson(STORAGE_KEYS.history, state.history); refreshHistory(); }
function addBookmark() { const url = addressBar.value.trim(); if (!url) return; const name = bookmarkName.value.trim() || url; state.bookmarks.unshift({ name, url }); saveJson(STORAGE_KEYS.bookmarks, state.bookmarks); bookmarkName.value = ''; refreshBookmarks(); }
function setTheme(theme) { state.theme = theme; state.settings.theme = theme; saveJson(STORAGE_KEYS.settings, state.settings); app.className = `app shell theme-${theme}`; window.browserAPI.setTheme(theme); }
function openCurrentInput() { const target = normalizeUrl(addressBar.value); const tab = state.tabs.find(item => item.id === state.activeTabId); if (tab) { tab.url = target; tab.title = target; loadTab(tab); renderTabs(); addHistory(target, tab.title); } else { createTab(target, target); } }
async function loadExtensionFromPicker() { const extensionDir = await window.browserAPI.pickExtensionDir(); if (!extensionDir) return; await window.browserAPI.loadExtension(extensionDir); }
async function saveSettings() { state.settings.homepage = homepageInput.value.trim() || defaultSettings.homepage; state.settings.searchEngine = searchEngineInput.value.trim() || defaultSettings.searchEngine; state.settings.openLinksInNewTab = openLinksInNewTabInput.checked; state.settings.downloadDir = downloadDirInput.value.trim(); await window.browserAPI.updateSettings(state.settings); saveJson(STORAGE_KEYS.settings, state.settings); }
async function resetSettings() { state.settings = { ...defaultSettings }; saveJson(STORAGE_KEYS.settings, state.settings); await window.browserAPI.updateSettings(state.settings); syncSettingsUI(); setTheme(state.settings.theme); }
async function saveAiConfig() { state.ai.model = aiModelSelect.value; const nextKey = aiKeyInput.value.trim(); if (nextKey && nextKey !== '********') state.ai.apiKey = nextKey; saveJson(STORAGE_KEYS.ai, state.ai); await window.browserAPI.writeAiConfig({ apiKey: state.ai.apiKey, model: state.ai.model }); aiKeyInput.value = '********'; }
async function clearAiConfig() { state.ai.apiKey = ''; state.ai.model = aiModelSelect.value; saveJson(STORAGE_KEYS.ai, state.ai); await window.browserAPI.writeAiConfig({ apiKey: '', model: state.ai.model }); aiKeyInput.value = ''; }
function hookShortcuts() { window.browserAPI.onShortcutNewTab(() => createTab()); window.browserAPI.onShortcutReopenTab(() => reopenClosedTab()); window.browserAPI.onShortcutHome(() => createTab(state.settings.homepage, '主页')); window.browserAPI.onShortcutDownloads(() => refreshDownloads()); window.browserAPI.onShortcutBookmarks(() => settingsPanel.classList.toggle('hidden', false)); window.browserAPI.onShortcutExtensions(() => settingsPanel.classList.toggle('hidden', false)); window.browserAPI.onShortcutSettings(() => settingsPanel.classList.toggle('hidden', false)); window.browserAPI.onShortcutFocusAddress(() => addressBar.focus()); window.browserAPI.onShortcutCloseTab(() => { const tab = state.tabs.find(item => item.id === state.activeTabId); if (tab) closeTab(tab.id); }); window.browserAPI.onShortcutNextTab(() => moveTab(1)); window.browserAPI.onShortcutPreviousTab(() => moveTab(-1)); window.browserAPI.onShortcutTabIndex((index) => activateTabByIndex(index)); window.browserAPI.onShortcutHistory(() => refreshHistory()); }

document.getElementById('newTabBtn').addEventListener('click', () => createTab()); document.getElementById('openFileBtn').addEventListener('click', async () => { const result = await window.browserAPI.openFile(); if (result?.url) createTab(result.url, result.type === 'pdf' ? 'PDF 文档' : '本地文件'); }); document.getElementById('goBtn').addEventListener('click', openCurrentInput); document.getElementById('quickStartBtn').addEventListener('click', () => createTab()); document.getElementById('refreshExtensionsBtn').addEventListener('click', refreshExtensions); document.getElementById('loadExtensionBtn').addEventListener('click', loadExtensionFromPicker); document.getElementById('backBtn').addEventListener('click', () => webview.canGoBack() && webview.goBack()); document.getElementById('forwardBtn').addEventListener('click', () => webview.canGoForward() && webview.goForward()); document.getElementById('reloadBtn').addEventListener('click', () => webview.reload()); document.getElementById('downloadBtn').addEventListener('click', () => refreshDownloads()); document.getElementById('bookmarkBtn').addEventListener('click', addBookmark); document.getElementById('settingsToggleBtn').addEventListener('click', () => settingsPanel.classList.toggle('hidden')); document.getElementById('homeBtn').addEventListener('click', () => createTab(state.settings.homepage, '主页')); document.getElementById('searchBtn').addEventListener('click', () => { if (searchInput.value.trim()) createTab(normalizeUrl(searchInput.value), searchInput.value); }); document.getElementById('themeGrid').addEventListener('click', (event) => { const theme = event.target.dataset.theme; if (theme) setTheme(theme); }); document.getElementById('saveSettingsBtn').addEventListener('click', saveSettings); document.getElementById('resetSettingsBtn').addEventListener('click', resetSettings); document.getElementById('pickDownloadDirBtn').addEventListener('click', async () => { const dir = await window.browserAPI.pickDownloadDir(); if (dir) downloadDirInput.value = dir; });
document.getElementById('aiToggleBtn').addEventListener('click', () => aiSidebar.classList.toggle('hidden')); document.getElementById('closeAiBtn').addEventListener('click', () => aiSidebar.classList.add('hidden')); document.getElementById('saveAiKeyBtn').addEventListener('click', saveAiConfig); document.getElementById('clearAiKeyBtn').addEventListener('click', clearAiConfig); document.getElementById('aiSendBtn').addEventListener('click', () => sendPrompt(aiPromptInput.value)); document.getElementById('aiClearChatBtn').addEventListener('click', () => { state.messages = []; renderAiChat(); }); document.getElementById('aiSendPageBtn').addEventListener('click', () => sendPrompt(getPageText())); aiPromptInput.addEventListener('keydown', (event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); sendPrompt(aiPromptInput.value); } });
webview.addEventListener('did-navigate', (event) => { const tab = state.tabs.find(item => item.id === state.activeTabId); if (tab) { tab.url = event.url; tab.title = (() => { try { return new URL(event.url).hostname || event.url; } catch { return event.url; } })(); addressBar.value = event.url; renderTabs(); addHistory(event.url, tab.title); } });
webview.addEventListener('page-title-updated', (event) => { const tab = state.tabs.find(item => item.id === state.activeTabId); if (tab) { tab.title = event.title; renderTabs(); addHistory(tab.url, event.title); } });
webview.addEventListener('new-window', (event) => { event.preventDefault(); const target = event.url || event.targetUrl; if (target) createTab(target, target); });
window.browserAPI.onThemeChanged((theme) => { state.theme = theme; app.className = `app shell theme-${theme}`; }); window.browserAPI.onSettingsUpdated((nextSettings) => { state.settings = { ...state.settings, ...nextSettings }; syncSettingsUI(); }); window.browserAPI.onAiConfigUpdated((config) => { if (config?.model) state.ai.model = config.model; if (typeof config?.hasApiKey === 'boolean') { if (!config.hasApiKey) state.ai.apiKey = ''; } syncSettingsUI(); }); window.browserAPI.onOpenUrl((value) => createTab(value, '本地 HTML')); window.browserAPI.onOpenPdf((value) => createTab(value, 'PDF 文档')); window.browserAPI.onDownloadsUpdated((downloads) => { state.downloads = downloads; refreshDownloads(); }); window.browserAPI.onExtensionsUpdated((extensions) => { state.extensions = extensions; refreshExtensions(); }); hookShortcuts(); renderAiChat();
window.browserAPI.getTheme().then(async (savedTheme) => { const nextSettings = await window.browserAPI.getSettings(); state.settings = { ...state.settings, ...nextSettings }; const aiConfig = await window.browserAPI.getAiConfig(); state.ai.model = aiConfig?.model || state.ai.model; if (!aiConfig?.hasApiKey) state.ai.apiKey = ''; syncSettingsUI(); const finalTheme = state.settings.theme || savedTheme; setTheme(finalTheme); refreshBookmarks(); refreshHistory(); refreshDownloads(); refreshExtensions(); toggleEmptyState(); createTab(state.settings.homepage, '主页'); });